58. Write a function to compute 5/0 and use try/except to catch the 
exceptions.

CODE:
def divide():
    return 5/0
try:
    divide()
except ZeroDivisionError as ze:
    print("Why are you dividing by ZERO!!")
except:
    print("Any other exceptions")